/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectcalculator;
/**
 * @author w.sullivan-DAVID GUTIERREZ SOLANO
 * @version Calculator 1.0v
 * @date 2016-03-02
 */
public class WindowStar extends javax.swing.JFrame {
    //Creating Attributes
    public String memory1;  //Variable Memory1 for Memory
    public String momory2;  //Variable Memory2 for Memory
    public boolean resultado1=true;
    public boolean resultado2=true;
    /**
     * Creates new form WindowStar
     */
    public WindowStar() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * Metodo para validar si hay punto o no en la operacion
     * @param coma  Recibe el parametro de la cantidad
     * @return resultado del boolean
     */
    public boolean presenciaComa(String coma){  //Se recibe parametro
        boolean resultado=false;    
        int indice=0;
        while(indice<coma.length()&&(coma.equals("."))){
            resultado=true;
            indice++;
        }
        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_MemorySum = new javax.swing.JButton();
        btn_MemoryLess = new javax.swing.JButton();
        btn_Percent = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btn_Multiplicar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btn_MOD = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btn_MemoryClearMC = new javax.swing.JButton();
        btn_MemoryRecallMR = new javax.swing.JButton();
        btn_MemoryStorage = new javax.swing.JButton();
        txt_ScreenOut = new javax.swing.JTextField();
        btn_ClearErrorCE = new javax.swing.JButton();
        btn_ClearC = new javax.swing.JButton();
        btn_MoreLess = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_Divisor = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_Resta = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_Coma = new javax.swing.JButton();
        btn_Suma = new javax.swing.JButton();
        btn_Resultado = new javax.swing.JButton();
        btn_Retroceso = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu_AboutCalculator = new javax.swing.JMenuItem();
        jMenu_ContactSupport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");
        setBackground(new java.awt.Color(234, 252, 255));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        btn_MemorySum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_MemorySum.setText("M+");
        btn_MemorySum.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_MemoryLess.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_MemoryLess.setText("M-");
        btn_MemoryLess.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_Percent.setText("%");
        btn_Percent.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_4.setText("4");
        btn_4.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_Multiplicar.setText("*");
        btn_Multiplicar.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_MOD.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_MOD.setText("MOD");
        btn_MOD.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_MemoryClearMC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_MemoryClearMC.setText("MC");
        btn_MemoryClearMC.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_MemoryRecallMR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_MemoryRecallMR.setText("MR");
        btn_MemoryRecallMR.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_MemoryStorage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_MemoryStorage.setText("MS");
        btn_MemoryStorage.setPreferredSize(new java.awt.Dimension(60, 40));

        txt_ScreenOut.setEditable(false);
        txt_ScreenOut.setBackground(new java.awt.Color(255, 255, 255));
        txt_ScreenOut.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txt_ScreenOut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_ScreenOut.setText("0");

        btn_ClearErrorCE.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_ClearErrorCE.setText("CE");
        btn_ClearErrorCE.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_ClearErrorCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearErrorCEActionPerformed(evt);
            }
        });

        btn_ClearC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_ClearC.setText("C");
        btn_ClearC.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_ClearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearCActionPerformed(evt);
            }
        });

        btn_MoreLess.setText("±");
        btn_MoreLess.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_7.setText("7");
        btn_7.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setText("8");
        btn_8.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setText("9");
        btn_9.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_Divisor.setText("/");
        btn_Divisor.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_1.setText("1");
        btn_1.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setText("2");
        btn_2.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_Resta.setText("-");
        btn_Resta.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_0.setText("0");
        btn_0.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_Coma.setText(",");
        btn_Coma.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_Coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComaActionPerformed(evt);
            }
        });

        btn_Suma.setText("+");
        btn_Suma.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_Resultado.setText("=");
        btn_Resultado.setPreferredSize(new java.awt.Dimension(60, 40));

        btn_Retroceso.setText("←");
        btn_Retroceso.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_Retroceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RetrocesoActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenu_AboutCalculator.setText("About Calculator");
        jMenu_AboutCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_AboutCalculatorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu_AboutCalculator);

        jMenu_ContactSupport.setText("Contact Support");
        jMenu_ContactSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ContactSupportActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu_ContactSupport);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Divisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Percent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_ClearErrorCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_ClearC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_MoreLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_MemoryLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_MemoryClearMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(btn_MemoryRecallMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_MemoryStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_MemorySum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_ScreenOut, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_MOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Coma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Retroceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(txt_ScreenOut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_MemoryClearMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MemoryRecallMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MemoryStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MemorySum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ClearErrorCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ClearC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MoreLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MemoryLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Divisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Percent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Retroceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Coma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Boton #9
    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"9"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_9ActionPerformed
    //Boton Item para llamar al Frame About Calculator
    private void jMenu_AboutCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_AboutCalculatorActionPerformed
        // TODO add your handling code here:
        AboutCalculator instanciaAboutCalculator=new AboutCalculator(this,true);    //Creacion de objeto instancia
        instanciaAboutCalculator.pack();    //Se instancia el paquete
        instanciaAboutCalculator.setVisible(true);  //Se instancia el metodo en true para mostrar el Frame
    }//GEN-LAST:event_jMenu_AboutCalculatorActionPerformed
    //Boton Item para llamar al Frame Contact Support
    private void jMenu_ContactSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ContactSupportActionPerformed
        // TODO add your handling code here:
        ContactSupport instanciaContactSupport=new ContactSupport(this,true);   //Creacion de objeto instancia
        instanciaContactSupport.pack(); //Se instancia el paquete
        instanciaContactSupport.setVisible(true);   //Se instancia el metodo en true para mostrar el Frame
    }//GEN-LAST:event_jMenu_ContactSupportActionPerformed
    //Boton #1
    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"1"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_1ActionPerformed
    //Boton #2
    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"2"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_2ActionPerformed
    //Boton #3
    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"3"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_3ActionPerformed
    //Boton #4
    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"4"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_4ActionPerformed
    //Boton #5
    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"5"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_5ActionPerformed
    //Boton #6
    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"6"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_6ActionPerformed
    //Boton #7
    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"7"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_7ActionPerformed
    //Boton #8
    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"8"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_8ActionPerformed
    //Boton #0
    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText(txt_ScreenOut.getText()+"0"); //Setear el TextFiel con el valor correspondiente del boton
    }//GEN-LAST:event_btn_0ActionPerformed
    //Boton del punto o coma
    private void btn_ComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComaActionPerformed
        // TODO add your handling code here:
        String coma=txt_ScreenOut.getText();  //Variable que captura el contenido del TextField
        if(coma.length()<=0){   //Se valida que coma no sea mayor que 0
            txt_ScreenOut.setText("0.");    //Seteamos
        }else if(!presenciaComa(txt_ScreenOut.getText())){
            txt_ScreenOut.setText(txt_ScreenOut.getText()+".");
        }
    }//GEN-LAST:event_btn_ComaActionPerformed
    //Boton para limpiar errores cortos
    private void btn_ClearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearCActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_btn_ClearCActionPerformed
    //Boton Clear Error o Borrar todo
    private void btn_ClearErrorCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearErrorCEActionPerformed
        // TODO add your handling code here:
        txt_ScreenOut.setText("0");  //Se limpia el TextFiel de pantalla
    }//GEN-LAST:event_btn_ClearErrorCEActionPerformed
    //Boton de Retroceso
    private void btn_RetrocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RetrocesoActionPerformed
        // TODO add your handling code here:
        String auxiliar=txt_ScreenOut.getText();    //Variable auxiliar para copiar el contenido del TextField de pantalla
            while(auxiliar.length()>0){ //Validar que la cadena auxiliar no este vacia
            auxiliar=auxiliar.substring(0,auxiliar.length()-1); //Auxiliar sera igual al auxiliar desde el indice 0 hasta el ultimo pero restando un indice
        }
        txt_ScreenOut.setText(auxiliar);    //Setear el TextFiel con auxiliar
    }//GEN-LAST:event_btn_RetrocesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowStar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowStar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowStar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowStar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowStar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_ClearC;
    private javax.swing.JButton btn_ClearErrorCE;
    private javax.swing.JButton btn_Coma;
    private javax.swing.JButton btn_Divisor;
    private javax.swing.JButton btn_MOD;
    private javax.swing.JButton btn_MemoryClearMC;
    private javax.swing.JButton btn_MemoryLess;
    private javax.swing.JButton btn_MemoryRecallMR;
    private javax.swing.JButton btn_MemoryStorage;
    private javax.swing.JButton btn_MemorySum;
    private javax.swing.JButton btn_MoreLess;
    private javax.swing.JButton btn_Multiplicar;
    private javax.swing.JButton btn_Percent;
    private javax.swing.JButton btn_Resta;
    private javax.swing.JButton btn_Resultado;
    private javax.swing.JButton btn_Retroceso;
    private javax.swing.JButton btn_Suma;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenu_AboutCalculator;
    private javax.swing.JMenuItem jMenu_ContactSupport;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txt_ScreenOut;
    // End of variables declaration//GEN-END:variables
}
